import type {
  Company,
  Subsidiary,
  Department,
  Employee,
} from "@av-crm/shared-types";

const now = () => new Date().toISOString();

export const COMPANIES: Company[] = [
  {
    id: "ak",
    name: "Akhlaq Ventures",
    description:
      "Parent company overseeing Akhlaq Ventures, Xenbus, and Xenbite.",
    logoUrl: "",
    securityLevel: "internal",
    createdAt: now(),
    updatedAt: now(),
  },
];

export const SUBSIDIARIES: Subsidiary[] = [
  {
    id: "xenbus",
    companyId: "ak",
    name: "Xenbus",
    description: "Enterprise SaaS platform.",
    securityLevel: "internal",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "xenbite",
    companyId: "ak",
    name: "Xenbite",
    description: "Consumer marketplace.",
    securityLevel: "internal",
    createdAt: now(),
    updatedAt: now(),
  },
];

export const DEPARTMENTS: Department[] = [
  {
    id: "xenbus-eng",
    companyId: "ak",
    subsidiaryId: "xenbus",
    name: "Engineering",
    description: "Platform and product engineering.",
    headId: "emp-xb-eng-head",
    securityLevel: "internal",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "xenbus-prod",
    companyId: "ak",
    subsidiaryId: "xenbus",
    name: "Product",
    description: "Product management and design.",
    headId: "emp-xb-prod-head",
    securityLevel: "internal",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "xenbus-sec",
    companyId: "ak",
    subsidiaryId: "xenbus",
    name: "Security",
    description: "Security operations and compliance.",
    headId: "emp-xb-sec-head",
    securityLevel: "confidential",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "xenbite-ops",
    companyId: "ak",
    subsidiaryId: "xenbite",
    name: "Operations",
    description: "Marketplace operations and support.",
    headId: "emp-xbi-ops-head",
    securityLevel: "internal",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "xenbite-mkt",
    companyId: "ak",
    subsidiaryId: "xenbite",
    name: "Marketing",
    description: "Brand, growth, and partnerships.",
    headId: "emp-xbi-mkt-head",
    securityLevel: "internal",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "ak-exec",
    companyId: "ak",
    subsidiaryId: "ak",
    name: "Executive",
    description: "C-suite and group leadership.",
    headId: "emp-ak-ceo",
    securityLevel: "restricted",
    createdAt: now(),
    updatedAt: now(),
  },
];

export const EMPLOYEES: Employee[] = [
  // Executive
  {
    id: "emp-ak-ceo",
    departmentId: "ak-exec",
    subsidiaryId: "ak",
    companyId: "ak",
    name: "Shiraz Akhlaq",
    email: "shiraz@akhlaqventures.com",
    title: "CEO",
    department: "Executive",
    securityLevel: "restricted",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },

  // Xenbus Engineering
  {
    id: "emp-xb-eng-head",
    departmentId: "xenbus-eng",
    subsidiaryId: "xenbus",
    companyId: "ak",
    name: "Priya Raman",
    email: "priya.raman@xenbus.io",
    title: "VP Engineering",
    department: "Engineering",
    securityLevel: "internal",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "emp-xb-eng-1",
    departmentId: "xenbus-eng",
    subsidiaryId: "xenbus",
    companyId: "ak",
    name: "Arjun Mehta",
    email: "arjun.mehta@xenbus.io",
    title: "Staff Engineer",
    department: "Engineering",
    securityLevel: "internal",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "emp-xb-eng-2",
    departmentId: "xenbus-eng",
    subsidiaryId: "xenbus",
    companyId: "ak",
    name: "Sara Khan",
    email: "sara.khan@xenbus.io",
    title: "Senior Engineer",
    department: "Engineering",
    securityLevel: "internal",
    isOnline: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "emp-xb-eng-3",
    departmentId: "xenbus-eng",
    subsidiaryId: "xenbus",
    companyId: "ak",
    name: "Daniel Okeke",
    email: "daniel.okeke@xenbus.io",
    title: "Engineer",
    department: "Engineering",
    securityLevel: "internal",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },

  // Xenbus Product
  {
    id: "emp-xb-prod-head",
    departmentId: "xenbus-prod",
    subsidiaryId: "xenbus",
    companyId: "ak",
    name: "Mei Tanaka",
    email: "mei.tanaka@xenbus.io",
    title: "Head of Product",
    department: "Product",
    securityLevel: "internal",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "emp-xb-prod-1",
    departmentId: "xenbus-prod",
    subsidiaryId: "xenbus",
    companyId: "ak",
    name: "Lucas Pereira",
    email: "lucas.pereira@xenbus.io",
    title: "Product Manager",
    department: "Product",
    securityLevel: "internal",
    isOnline: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "emp-xb-prod-2",
    departmentId: "xenbus-prod",
    subsidiaryId: "xenbus",
    companyId: "ak",
    name: "Aisha Mwangi",
    email: "aisha.mwangi@xenbus.io",
    title: "Product Designer",
    department: "Product",
    securityLevel: "internal",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },

  // Xenbus Security
  {
    id: "emp-xb-sec-head",
    departmentId: "xenbus-sec",
    subsidiaryId: "xenbus",
    companyId: "ak",
    name: "Mateo Alvarez",
    email: "mateo.alvarez@xenbus.io",
    title: "CISO",
    department: "Security",
    securityLevel: "confidential",
    isOnline: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "emp-xb-sec-1",
    departmentId: "xenbus-sec",
    subsidiaryId: "xenbus",
    companyId: "ak",
    name: "Yuki Sato",
    email: "yuki.sato@xenbus.io",
    title: "Security Engineer",
    department: "Security",
    securityLevel: "confidential",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },

  // Xenbite Operations
  {
    id: "emp-xbi-ops-head",
    departmentId: "xenbite-ops",
    subsidiaryId: "xenbite",
    companyId: "ak",
    name: "Fatima Haidari",
    email: "fatima.haidari@xenbite.io",
    title: "Head of Operations",
    department: "Operations",
    securityLevel: "internal",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "emp-xbi-ops-1",
    departmentId: "xenbite-ops",
    subsidiaryId: "xenbite",
    companyId: "ak",
    name: "Ravi Krishnan",
    email: "ravi.krishnan@xenbite.io",
    title: "Operations Analyst",
    department: "Operations",
    securityLevel: "internal",
    isOnline: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "emp-xbi-ops-2",
    departmentId: "xenbite-ops",
    subsidiaryId: "xenbite",
    companyId: "ak",
    name: "Hannah Lindqvist",
    email: "hannah.lindqvist@xenbite.io",
    title: "Customer Success",
    department: "Operations",
    securityLevel: "internal",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },

  // Xenbite Marketing
  {
    id: "emp-xbi-mkt-head",
    departmentId: "xenbite-mkt",
    subsidiaryId: "xenbite",
    companyId: "ak",
    name: "Carlos Mendoza",
    email: "carlos.mendoza@xenbite.io",
    title: "Head of Marketing",
    department: "Marketing",
    securityLevel: "internal",
    isOnline: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "emp-xbi-mkt-1",
    departmentId: "xenbite-mkt",
    subsidiaryId: "xenbite",
    companyId: "ak",
    name: "Naledi Khumalo",
    email: "naledi.khumalo@xenbite.io",
    title: "Growth Manager",
    department: "Marketing",
    securityLevel: "internal",
    isOnline: false,
    createdAt: now(),
    updatedAt: now(),
  },
];
